version: '3.8'

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.0
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      QUERY_DEFAULTS_LIMIT: 250000
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
      # Add a longer startup timeout to wait for the i2v-neural service
      STARTUP_TIMEOUT: '60s'
    depends_on:
      i2v-neural:
        condition: service_started
  
  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'
    # Using wget for health check as it's more commonly available in base images
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/.well-known/ready || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
  
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - WEAVIATE_URL=http://weaviate:8080
      # Add your environment variables here or use env_file
    env_file:
      - .env
    depends_on:
      weaviate:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./src:/app/src  # For hot-reloading in development
      - ./public:/app/public # For static files if needed
    # Add a simple TCP connection check as a health check
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s